/**
 * Bundles the Carbon's hand-written agent files at build time: web/llms/llms.md (served at /llms.txt) and
 * web/llms/llms-full.md (served at /llms-full.txt; when it is missing, /llms-full.txt serves llms.md) into
 * lib/agent/generated/llms.ts, exactly as written, with when each last changed (git, or the file's time while it has
 * changes of its own). Nothing reads web/llms/ at run time. Never edit the .md files from code.
 *
 *   tsx lib/agent/build-llms.ts            write the module (pnpm dev, build, typecheck and test run it first)
 *   tsx lib/agent/build-llms.ts --check    fail when the module is out of date
 *   tsx lib/agent/build-llms.ts --quiet    no output unless something is wrong
 */
import { execFileSync } from "node:child_process";
import { existsSync, mkdirSync, readFileSync, renameSync, statSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const webRoot = join(dirname(fileURLToPath(import.meta.url)), "..", "..");
const llmsDir = join(webRoot, "llms");
const output = join(webRoot, "lib", "agent", "generated", "llms.ts");
const NAMES = ["llms.md", "llms-full.md"] as const;

function git(args: string[]): string | null {
  try {
    return execFileSync("git", args, { cwd: llmsDir, encoding: "utf8", stdio: ["ignore", "pipe", "ignore"] });
  } catch {
    return null;
  }
}

/** When each file last changed: its last commit, or its own time while it has uncommitted changes or none at all. */
function modified(name: string): string | null {
  const path = join(llmsDir, name);
  if (!existsSync(path)) return null;
  const dirty = (git(["status", "--porcelain", "--", name]) ?? "").trim() !== "";
  const committed = dirty ? "" : (git(["log", "-1", "--format=%cI", "--", name]) ?? "").trim();
  return committed ? new Date(committed).toISOString() : statSync(path).mtime.toISOString();
}

function read(name: string): string | null {
  const path = join(llmsDir, name);
  return existsSync(path) ? readFileSync(path, "utf8") : null;
}

function llmsModule(): string {
  const [index, full] = NAMES.map(read);
  const [indexModified, fullModified] = NAMES.map(modified);
  return [
    "/* Generated by lib/agent/build-llms.ts from web/llms/: do not edit. Run `pnpm build:llms` (pnpm dev and pnpm build do). */",
    "",
    "/** web/llms/llms.md exactly as written, served at /llms.txt (null: the file is missing). */",
    `export const LLMS_TXT: string | null = ${JSON.stringify(index)};`,
    "/** web/llms/llms-full.md exactly as written, served at /llms-full.txt (null: missing, /llms-full.txt serves llms.md). */",
    `export const LLMS_FULL_TXT: string | null = ${JSON.stringify(full)};`,
    `export const LLMS_TXT_MODIFIED: string | null = ${JSON.stringify(indexModified)};`,
    `export const LLMS_FULL_TXT_MODIFIED: string | null = ${JSON.stringify(fullModified)};`,
    "",
  ].join("\n");
}

/** The generated module without its dates, for --check (a fresh checkout's file times differ from the build's). */
const withoutDates = (text: string) => text.replace(/^export const LLMS_(FULL_)?TXT_MODIFIED.*$/gm, "");

function main() {
  const args = new Set(process.argv.slice(2));
  const content = llmsModule();
  if (!existsSync(join(llmsDir, "llms.md"))) console.warn("build:llms: web/llms/llms.md is missing, so /llms.txt answers 404");
  if (args.has("--check")) {
    const current = existsSync(output) ? readFileSync(output, "utf8") : "";
    if (withoutDates(current) !== withoutDates(content)) {
      console.error("build:llms: lib/agent/generated/llms.ts is out of date with web/llms/. Run `pnpm build:llms`.");
      process.exit(1);
    }
    return;
  }
  const current = existsSync(output) ? readFileSync(output, "utf8") : null;
  if (current === content) return;
  mkdirSync(dirname(output), { recursive: true });
  const temporary = `${output}.${process.pid}.tmp`;
  writeFileSync(temporary, content);
  renameSync(temporary, output);
  if (!args.has("--quiet")) console.log("build:llms: wrote lib/agent/generated/llms.ts");
}

main();
