//! The words client telemetry is forwarded with (`POST /v1/telemetry/events`, the parent
//! module): exactly what the silicon-accounts CLI reports. An event is forwarded only from a
//! known [`SOURCES`] entry under a known [`NAMES`] entry; its `step`, and its `command`, `os`,
//! `arch` and `error_code` fields, only as one of the words below, and as `other` when they are
//! anything else. So nothing a client makes up (an email, a name, a path, a uuid, a si:id) ever
//! reaches Space Station, whatever its shape.
//!
//! Plain data with no dependencies: the CLI's tests include this file to check that every
//! command path and step it can report is listed (crates/cli/tests/telemetry_lists.rs), and the
//! server's tests check every error code the service and the CLI can give
//! (crates/server/tests/telemetry_lists.rs). A word missing here is forwarded as `other`.

/// Where events come from: the CLI.
pub const SOURCES: &[&str] = &["cli"];

/// Event names: a step of a multi-step flow, and the end of a command.
pub const NAMES: &[&str] = &["cli.command", "cli.step"];

/// The CLI's step names (`cli.step` events).
pub const STEPS: &[&str] = &[
    "app.import.started",
    "login.code.sent",
    "login.device.approved",
    "login.device.code_shown",
    "login.done",
    "login.federated.started",
    "login.silicon.started",
    "login.silicon_key.started",
    "login.slt.issued",
    "session.reexchanged",
    "session.refreshed",
    "silicon.create.accepted",
    "silicon.create.custodian",
    "silicon.create.requested",
    "token.identity.issued",
];

/// Every command path of the CLI (`app webhook set`): the `step` of a `cli.command` event and
/// the `command` field of every event.
pub const COMMANDS: &[&str] = &[
    "accounts",
    "app",
    "app config",
    "app config get",
    "app config history",
    "app config set",
    "app import",
    "app import list",
    "app import rows",
    "app import status",
    "app list",
    "app lookup",
    "app new",
    "app proof",
    "app proof app-verification",
    "app proof list",
    "app proof refresh",
    "app proof revoke",
    "app proof user-verification",
    "app proof verify",
    "app show",
    "app subscription",
    "app subscription create",
    "app subscription delete",
    "app subscription list",
    "app subscription show",
    "app subscription test",
    "app subscription update",
    "app token",
    "app token exchange",
    "app token introspect",
    "app token refresh",
    "app token revoke",
    "app token slt",
    "app token verify",
    "app use",
    "app user",
    "app userinfo",
    "app users",
    "app webhook",
    "app webhook deliveries",
    "app webhook delivery",
    "app webhook remove",
    "app webhook replay",
    "app webhook rotate",
    "app webhook set",
    "app webhook test",
    "apps",
    "apps list",
    "apps remove",
    "config",
    "config get",
    "config home",
    "config set",
    "config telemetry",
    "config unset",
    "custodian",
    "custodian accept",
    "custodian decline",
    "custodian requests",
    "delete-account",
    "device",
    "device approve",
    "device deny",
    "device show",
    "docs",
    "email",
    "email add",
    "email list",
    "email primary",
    "email remove",
    "email verify",
    "help",
    "history",
    "id",
    "id available",
    "id change",
    "identities",
    "identities list",
    "identities remove",
    "login",
    "login status",
    "logout",
    "lookup",
    "phone",
    "phone add",
    "phone list",
    "phone primary",
    "phone remove",
    "phone verify",
    "profile",
    "profile set",
    "profile show",
    "proofs",
    "proofs list",
    "proofs revoke",
    "report",
    "sessions",
    "sessions list",
    "sessions revoke",
    "silicon",
    "silicon apps",
    "silicon apps allow",
    "silicon apps allowed",
    "silicon apps list",
    "silicon apps remove",
    "silicon audiences",
    "silicon audiences allow",
    "silicon audiences list",
    "silicon audiences remove",
    "silicon cancel-transfer",
    "silicon create",
    "silicon delete",
    "silicon id",
    "silicon keys",
    "silicon keys add",
    "silicon keys list",
    "silicon keys revoke",
    "silicon list",
    "silicon request",
    "silicon request status",
    "silicon rotate-stk",
    "silicon show",
    "silicon signins",
    "silicon transfer",
    "silicon trust",
    "silicon trust add",
    "silicon trust list",
    "silicon trust remove",
    "silicon update",
    "silicon webhook",
    "silicon webhook deliveries",
    "silicon webhook delivery",
    "silicon webhook remove",
    "silicon webhook replay",
    "silicon webhook set",
    "token",
    "token identity",
    "webhook",
    "webhook deliveries",
    "webhook delivery",
    "webhook remove",
    "webhook replay",
    "webhook set",
    "webhook test",
    "whoami",
];

/// Operating systems, as Rust's `std::env::consts::OS` names them.
pub const OS: &[&str] = &[
    "linux",
    "macos",
    "windows",
    "freebsd",
    "openbsd",
    "netbsd",
    "dragonfly",
    "solaris",
    "illumos",
    "android",
    "ios",
    "tvos",
    "watchos",
    "visionos",
    "aix",
    "haiku",
    "fuchsia",
    "redox",
    "hurd",
    "cygwin",
];

/// Processor architectures, as Rust's `std::env::consts::ARCH` names them.
pub const ARCH: &[&str] = &[
    "x86_64",
    "aarch64",
    "x86",
    "arm",
    "arm64ec",
    "riscv64",
    "riscv32",
    "powerpc",
    "powerpc64",
    "s390x",
    "loongarch64",
    "mips",
    "mips64",
    "mips32r6",
    "mips64r6",
    "sparc",
    "sparc64",
    "m68k",
    "csky",
    "wasm32",
    "wasm64",
    "hexagon",
    "xtensa",
];

/// Error codes the CLI can end with: the service's (its API and OAuth errors), the Rust
/// client's and the CLI's own.
pub const ERROR_CODES: &[&str] = &[
    "access_denied",
    "access_removed",
    "account_auth_required",
    "account_changed",
    "account_deleted",
    "account_not_active",
    "account_not_found",
    "account_not_unclaimed",
    "account_unavailable",
    "already_custodian",
    "app_credentials_required",
    "app_disabled",
    "app_mismatch",
    "app_not_allowed",
    "app_verification_single_app",
    "audience_not_allowed",
    "author_not_found",
    "authorization_pending",
    "browser_session_required",
    "cannot_remove_primary",
    "capabilities_missing",
    "carbon_only",
    "challenge_not_found",
    "code_already_used",
    "code_expired",
    "config_version_conflict",
    "confirmation_mismatch",
    "confirmation_required",
    "connection_failed",
    "continue_not_allowed",
    "corrupt_state_file",
    "custodian_declined",
    "custodian_expired",
    "custodian_not_found",
    "custodian_of_silicons",
    "custodian_only",
    "custodian_pending",
    "custodian_request_expired",
    "custodian_request_not_found",
    "custodian_request_not_pending",
    "custodian_request_pending",
    "custodian_required",
    "database_unavailable",
    "delivery_not_found",
    "detail_not_on_page",
    "dev_outbox_disabled",
    "device_code_expired",
    "device_code_not_found",
    "device_code_used",
    "device_flow_off",
    "dob_immutable",
    "duplicate_columns",
    "email_domain_not_allowed",
    "email_in_use",
    "empty_import",
    "empty_photo",
    "expired_token",
    "external_id_conflict",
    "federated_session",
    "federation_exists",
    "federation_not_found",
    "file_not_found",
    "first_party_app",
    "flow_changed",
    "flow_completed",
    "flow_expired",
    "flow_failed",
    "flow_not_bound",
    "flow_not_found",
    "id_reserved",
    "id_taken",
    "idempotency_in_progress",
    "idempotency_key_required",
    "idempotency_key_reused",
    "idempotency_result_unavailable",
    "identity_in_use",
    "identity_not_found",
    "identity_token_not_accepted",
    "import_not_found",
    "import_upload_too_slow",
    "imports_busy",
    "internal",
    "internal_api_disabled",
    "internal_token_required",
    "interrupted",
    "invalid_app_credentials",
    "invalid_arguments",
    "invalid_assertion",
    "invalid_authorization",
    "invalid_authors",
    "invalid_body",
    "invalid_client",
    "invalid_code",
    "invalid_content_type",
    "invalid_credentials",
    "invalid_csv",
    "invalid_cursor",
    "invalid_federated_token",
    "invalid_grant",
    "invalid_history_kind",
    "invalid_id",
    "invalid_idempotency_key",
    "invalid_image",
    "invalid_input",
    "invalid_internal_token",
    "invalid_json",
    "invalid_path",
    "invalid_proof_id",
    "invalid_proof_refresh_token",
    "invalid_provider",
    "invalid_query",
    "invalid_receiving_app",
    "invalid_request",
    "invalid_request_token",
    "invalid_scope",
    "invalid_state",
    "invalid_step",
    "invalid_stk",
    "invalid_subject_token",
    "invalid_token",
    "invalid_updates",
    "invalid_url",
    "invalid_uuid",
    "invalid_webhook_events",
    "io_error",
    "issuer_unavailable",
    "issuer_unreachable",
    "key_exists",
    "key_not_found",
    "last_sign_in_method",
    "login_locked",
    "membership_inactive",
    "membership_not_found",
    "method_not_allowed",
    "method_not_enabled",
    "no_code_sent",
    "no_identifier_columns",
    "no_matching_trust",
    "no_previous_page",
    "not_a_directory",
    "not_app_owner",
    "not_found",
    "not_issuing_app",
    "not_signed_in",
    "origin_not_allowed",
    "owner_email_conflict",
    "owner_not_author",
    "owner_not_found",
    "owner_unavailable",
    "payload_too_large",
    "phone_in_use",
    "photo_dimensions_too_large",
    "photo_not_found",
    "photo_too_large",
    "photo_type_mismatch",
    "proof_expired",
    "proof_not_found",
    "proof_refresh_token_reused",
    "proof_revoked",
    "provider_not_configured",
    "rate_limited",
    "reauthentication_required",
    "receiving_app_disabled",
    "redirect_uri_not_registered",
    "request_timeout",
    "request_token_required",
    "requirements_missing",
    "route_not_found",
    "server_error",
    "session_changed",
    "session_ended",
    "session_expired",
    "session_not_found",
    "session_required",
    "signup_already_completed",
    "signup_expired",
    "signup_not_allowed",
    "signup_not_bound",
    "silicon_not_active",
    "silicon_not_found",
    "silicon_not_pending",
    "silicon_only",
    "slow_down",
    "stream_capacity_reached",
    "stream_subscription_required",
    "subject_token_wrong_app",
    "subscription_exists",
    "subscription_not_found",
    "timed_out",
    "token_bad_signature",
    "token_expired",
    "token_invalid_key",
    "token_malformed",
    "token_missing_claim",
    "token_not_yet_valid",
    "token_revoked",
    "token_unknown_key",
    "token_unsupported_algorithm",
    "token_wrong_audience",
    "token_wrong_issuer",
    "too_many_columns",
    "too_many_federations",
    "too_many_items",
    "too_many_keys",
    "too_many_rows",
    "too_many_streams",
    "transfer_not_found",
    "transfer_pending",
    "transfer_stale",
    "transfer_to_self",
    "unauthenticated",
    "unauthorized_client",
    "unexpected_response",
    "unknown_app",
    "unknown_columns",
    "unknown_event_id",
    "unknown_help_topic",
    "unknown_provider",
    "unknown_receiving_app",
    "unknown_topic",
    "unsupported_grant_type",
    "unsupported_media_type",
    "unsupported_version",
    "user_not_found",
    "validation_failed",
    "value_too_large",
    "verification_locked",
    "verification_not_found",
    "verified_email_missing",
    "web_not_built",
    "webhook_not_set",
    "wrong_account_kind",
];
